version: '3'
services:
  slash:
    image: ghcr.io/didid08/slash:latest
    container_name: slash
    ports:
      - 5231:5231
    volumes:
      - slash:/var/opt/slash
    restart: always

volumes:
  slash: